name: Streamlit App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Streamlit smoke & lint
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app/app.py
          ruff: true